name       : kitty
version    : 0.11.3
release    : 5
source     :
    - https://github.com/kovidgoyal/kitty/archive/v0.11.3.tar.gz : f0e1f0972fcee141c05caac543ef017ee7c87ddddf5fde636c614a28e45021c3
license    : GPL-3.0-only
component  : system.utils
summary    : Fast, feature full, GPU based terminal emulator
description: |
    Kitty is designed for power keyboard users. To that end all its controls work with the keyboard (although it fully supports mouse interactions as well). Its configuration is a simple, human editable, single file for easy reproducibility.

    Kitty is designed from the ground up to support all modern terminal features, such as unicode, true color, bold/italic fonts, text formatting, etc. It even extends existing text formatting escape codes, to add support for features not available elsewhere, such as colored and styled (curly) underlines. One of the design goals of Kitty is to be easily extensible so that new features can be added in the future with relatively less effort.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(libpng)
    - pkgconfig(python3)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - libunistring-devel
    - python-sphinx
install    : |
    python3 setup.py linux-package --prefix $installdir/usr
